services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    ports:
      - 11434:11434
    volumes:
      - ./data/ollama:/root/.ollama
    # GPU support
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities:
    #             - gpu

  # webui, nagivate to http://localhost:3000/ to use
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    pull_policy: always
    # user: 111:1001
    volumes:
      - ./data/webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - 3000:8080
    environment:
      - "OLLAMA_API_BASE_URL=http://ollama:11434/api"
      - OLLAMA_BASE_URLS=http://ollama:11434
      - ENV=dev
      - WEBUI_AUTH=False
      - WEBUI_NAME=LLM Playground
      - WEBUI_URL=http://localhost:8080
      - WEBUI_SECRET_KEY=super-key
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped